/* Progressive enhancements. All cases remain readable without JavaScript. */
(() => {
 const copy = {
 en:{heroEyebrow:'MIKHAIL / GENERATIVE AI ENGINEER',heroTitle:'Creative output.<br><em>Engineered<br>to repeat.</em>',heroLede:'I turn complex image-generation tasks into controlled ComfyUI workflows. Virtual try-on, product imagery and consistent characters — built for production, not just a good first frame.',heroLink:'Explore selected work',discussProject:'Discuss a project ↗',selectedEyebrow:'01 / SELECTED WORK',selectedTitle:'The image is the proof.<br>The system is the work.',selectedBody:'Independent, synthetic case studies in fidelity, consistency and control. Explore the images, then open a case to see the inputs, outputs and constraints. Production workflows stay private.',visualLabel:'CONTROLLED GENERATION',visualCaption:'Different worlds. Same attention to detail.',filterAll:'All work',filterFashion:'Fashion',filterCommercial:'Product & story',filterSpaces:'Spaces',exploreCase:'Explore case',profileEyebrow:'02 / THE ENGINEER',profileTitle:'Creative ambition.<br>Production discipline.',privateEyebrow:'03 / UNDER THE HOOD',privateTitle:'Not just a workflow.<br>A system you can run.',deliveryEyebrow:'04 / HOW WE START',deliveryTitle:'Your inputs.<br>A working proof.',contactEyebrow:'PAID TECHNICAL TEST · RETAINER · R&D',contactTitle:'A real challenge?<br><em>Let’s build the workflow.</em>',project1:'Virtual try-on',project2:'Fashion, in context',project3:'A menu, not a one-off',project4:'One product. New spaces.',project5:'Spaces, reimagined',project6:'Identity is the constant',projectDesc1:'Garment fidelity · matched poses',projectDesc2:'Five garments · five scenes',projectDesc3:'Art direction · consistent series',projectDesc4:'Product identity · spatial control',projectDesc5:'Staging · cleanup · day to dusk',projectDesc6:'Characters · watches · jewellery'},
 ru:{navProduction:'Подход',heroEyebrow:'МИХАИЛ / GENERATIVE AI ENGINEER',heroTitle:'Креативный результат.<br><em>Повторяемый<br>по замыслу.</em>',heroLede:'Превращаю сложные задачи генерации изображений в управляемые ComfyUI-workflow. Виртуальная примерка, продуктовые кадры и постоянство персонажей — не только удачный кадр, а рабочая система.',heroLink:'Смотреть работы',discussProject:'Обсудить проект ↗',selectedEyebrow:'01 / ИЗБРАННЫЕ РАБОТЫ',selectedTitle:'Изображение — результат.<br>Система — моя работа.',selectedBody:'Независимые синтетические кейсы о точности, постоянстве и контроле. Посмотрите работы и раскройте кейс: внутри — исходники, результаты и ограничения. Production-workflow остаются закрытыми.',visualLabel:'УПРАВЛЯЕМАЯ ГЕНЕРАЦИЯ',visualCaption:'Разные миры. Одинаковое внимание к деталям.',filterAll:'Все работы',filterFashion:'Мода',filterCommercial:'Продукт и сюжет',filterSpaces:'Пространства',exploreCase:'Смотреть кейс',profileEyebrow:'02 / ОБ ИНЖЕНЕРЕ',profileTitle:'Креативный замысел.<br>Инженерная точность.',privateEyebrow:'03 / ПОД КАПОТОМ',privateTitle:'Не просто workflow.<br>Система для работы.',deliveryEyebrow:'04 / С ЧЕГО НАЧНЁМ',deliveryTitle:'Ваши исходники.<br>Рабочий результат.',contactEyebrow:'ТЕХНИЧЕСКИЙ ТЕСТ · СОПРОВОЖДЕНИЕ · R&D',contactTitle:'Есть сложная задача?<br><em>Построим workflow.</em>',project1:'Виртуальная примерка',project2:'Одежда в новом контексте',project3:'Не один кадр, а целое меню',project4:'Один продукт. Новые пространства.',project5:'Пространство по-новому',project6:'Идентичность — неизменна',projectDesc1:'Точность одежды · сохранение поз',projectDesc2:'Пять вещей · пять сцен',projectDesc3:'Арт-дирекция · единая серия',projectDesc4:'Идентичность продукта · пространство',projectDesc5:'Меблировка · очистка · сумерки',projectDesc6:'Персонажи · часы · украшения'}
 };
 Object.assign(translations.en,copy.en);Object.assign(translations.ru,copy.ru);
 const cards=[...document.querySelectorAll('.project-card')], filters=[...document.querySelectorAll('[data-filter]')];
 function count(){const n=cards.filter(x=>!x.hidden).length;document.querySelector('.work-count').textContent=document.documentElement.lang==='ru'?`${n} / 6 кейсов`:`${n} / 6 case studies`;}
 const base=setLanguage;
 setLanguage=function(lang){base(lang==='ru'?'ru':'en');const ru=document.documentElement.lang==='ru';closeButton.textContent=ru?'Закрыть ×':'Close ×';closeButton.setAttribute('aria-label',ru?'Закрыть изображение':'Close image viewer');dialog.setAttribute('aria-label',ru?'Просмотр изображения':'Image viewer');document.querySelector('.theme-toggle').setAttribute('aria-label',ru?'Переключить светлую и тёмную тему':'Toggle light and dark theme');count();};
 filters.forEach(b=>b.addEventListener('click',()=>{filters.forEach(x=>x.setAttribute('aria-pressed',String(x===b)));cards.forEach(x=>x.hidden=b.dataset.filter!=='all'&&x.dataset.category!==b.dataset.filter);count();}));
 function revealHash(){let id;try{id=decodeURIComponent(location.hash.slice(1));}catch(_){return;}if(!id)return;const t=document.getElementById(id);if(!t)return;const d=t.closest('details');if(d)d.open=true;requestAnimationFrame(()=>(d||t).scrollIntoView({block:'start',behavior:'auto'}));}
 cards.forEach(c=>c.addEventListener('click',()=>{const d=document.getElementById(c.hash.slice(1))?.closest('details');if(d)d.open=true;if(location.hash===c.hash)revealHash();}));
 window.addEventListener('hashchange',revealHash);
 document.querySelectorAll('.case-detail').forEach(d=>d.addEventListener('toggle',()=>d.querySelectorAll('.reveal').forEach(x=>x.classList.add('is-visible'))));
 function themeMeta(){const r=document.documentElement;const dark=r.dataset.theme?r.dataset.theme==='dark':matchMedia('(prefers-color-scheme: dark)').matches;document.querySelector('meta[name="theme-color"]').content=dark?'#171a18':'#f7f7f2';}
 document.querySelector('.theme-toggle').addEventListener('click',()=>{const r=document.documentElement;const dark=r.dataset.theme?r.dataset.theme==='dark':matchMedia('(prefers-color-scheme: dark)').matches;r.dataset.theme=dark?'light':'dark';themeMeta();try{localStorage.setItem('northstar-theme',r.dataset.theme);}catch(_){}});
 try{const theme=localStorage.getItem('northstar-theme');if(theme==='light'||theme==='dark')document.documentElement.dataset.theme=theme;}catch(_){}
 document.documentElement.classList.add('js');themeMeta();setLanguage(document.documentElement.lang);revealHash();
})();
